language: php
php:
- '5.4'
- '5.3'
- '5.2'
before_script:
- pear install --alldeps pear/PHP_CodeSniffer
- phpenv rehash
script:
- phpcs --extensions=php -p --standard=PSR2 ./
notifications:
  slack:
    secure: Mal7CdbCv4wQRvV+teWbs/wOwvIGFrq31b1gR9dypFG8wjvsClSm2gfkfQcp9O3dpZa/aMS2X04cBSO7SyyEIeSnhR6wKYdYyi+IL3LyvEZ1957n4cb7cC9XYbIHzl8T8G9oE8Y+hPQTpcDqeo+D4mvLLdslR2dz5u1vgqc+DEI=
