
<?php foreach ($this->getItems() as $_item): ?>
    <option value="<?php if ($_item->getCount() > 0) echo $this->urlEscape($_item->getUrl()) ?>">
        <?php if ($_item->getCount() > 0): ?>
        
        	<?php echo $_item->getLabel() ?>
        
        <?php else: echo $_item->getLabel() ?>
        <?php endif; ?>
        <?php if ($this->shouldDisplayProductCount()): ?>
        (<?php echo $_item->getCount() ?>)
        <?php endif; ?>
    </option>
<?php endforeach ?>

