<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): 
	$_products->clear()
                    ->setPageSize(3)
                    ->load();
?>
<div>
    <h4><?php echo $this->__('Top 3 bestseller') ?></h4>
	<?php echo $this->getPagerHtml() ?>

	<?php  foreach ($_products->getItems() as $_product):  ?>
		<div class="event-sidebar">
			<div class="img-event-sidebar">
				<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(50) ?>" width="50" height="50" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" /></a>
			</div>
			<div class="desc-event-sidebar">
				<?php 
					$arr = explode(" ",$this->helper('catalog/output')->productAttribute($_product, $_product->getShortDescription(), 'short_description'));
					$desc = "";
					$i = 0;
					do {
						$desc .= $arr[$i];
						$desc .= " ";
						$i++;
					} while (strlen($desc) <70);
					$desc .= "..."; 
				?>
				<p><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $desc; ?></a></p>
			</div>
		</div>
		<div class="clear"></div>
	<?php endforeach; ?>
	
</div>
<?php endif; ?>